version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: motio-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: motio
      POSTGRES_USER: motio_admin
      POSTGRES_PASSWORD: motio_password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always

  motio-core:
    image: motio-core
    container_name: motio-core
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    restart: always

  motio-auth:
    image: motio-auth
    container_name: motio-auth
    depends_on:
      - motio-core
    ports:
      - "8070:8070"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    restart: always

  motio-admin:
    image: motio-admin
    container_name: motio-admin
    depends_on:
      - motio-core
    ports:
      - "8060:8060"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  motio-web-admin:
    image: motio-web-admin
    container_name: motio-web-admin
    ports:
      - "3000:3000"
    environment:
      REACT_APP_CORE_API_URL: ${REACT_APP_CORE_API_URL}
      REACT_APP_AUTH_API_URL: ${REACT_APP_AUTH_API_URL}
      REACT_APP_ADMIN_API_URL: ${REACT_APP_ADMIN_API_URL}
    restart: always

  motio-postgres-backup:
    image: motio-postgres-backup
    container_name: motio-postgres-backup
    volumes:
      - ./backups:/backups
    environment:
      POSTGRES_DB: motio
      POSTGRES_USER: motio_admin
      POSTGRES_PASSWORD: motio_password
    depends_on:
      - postgres
    restart: always
